# Generated by Django 3.2.7 on 2021-09-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('date_installation', models.DateTimeField(blank=True, null=True, verbose_name='Дата монтажа')),
                ('date_unistall', models.DateTimeField(blank=True, null=True, verbose_name='Дата демонтажа')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_number', models.CharField(max_length=50, verbose_name='Номер двигателя')),
                ('date_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='count.datecheck')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.CharField(max_length=50, verbose_name='Номер станции')),
                ('date_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='count.datecheck', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OT_in_day', models.IntegerField(verbose_name='Наработка за сутки')),
                ('max_power', models.IntegerField(blank=True, verbose_name='Максимальная нагрузка')),
                ('max_temperature', models.FloatField(blank=True, verbose_name='Максимальная температура')),
                ('duty_officer', models.CharField(max_length=255, verbose_name='Оперативный дежурный ФИО')),
                ('volume_oil', models.IntegerField(verbose_name='Уровень масла')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('time_work', models.DateTimeField(verbose_name='Дата')),
                ('journal', models.TextField(blank=True, max_length=500, verbose_name='Произведенные работы')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='Статус')),
                ('TO', models.BooleanField(default=False, verbose_name='Техническое обслуживание')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='count.engine', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='gas_par',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_gas', models.IntegerField(blank=True, default=0, verbose_name='Расход газа')),
                ('gas_temperature', models.FloatField(blank=True, default=0, verbose_name='Температура газа')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='count.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Потребление газа',
                'verbose_name_plural': 'Потребление газа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnergyGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_active', models.FloatField(blank=True, default=0, verbose_name='Активная мощность')),
                ('power_react', models.FloatField(blank=True, default=0, verbose_name='Реактивная мощность')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='count.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Выработка электроэнергии',
                'verbose_name_plural': 'Выработка электроэнергии',
                'ordering': ['id'],
            },
        ),
    ]
