# Generated by Django 3.2.7 on 2021-09-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='count.station', verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='count.engine', verbose_name='Двигатель'),
        ),
    ]
